import type { NextPage } from "next";
import Head from "next/head";
import { Hero } from "../components/Hero";

import { Header } from "../components/Header";

const Home: NextPage = () => {
  return (
    <div className="">
      <Head>
        <title>Vesting Dapp</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <Header />
      <main>
        <Hero />
      </main>
    </div>
  );
};

export default Home;
