import type { NextPage } from "next";
import Head from "next/head";
import { Header } from "../../components/Header";
import { CreateCompany } from "../../components/CreateCompany";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Vesting Dapp</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <main>
        <Header />
        <CreateCompany />
      </main>
    </div>
  );
};

export default Home;
